// <auto-generated />
namespace Bugtracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class appuser_remove_nav_prop_tickethistories___tickethistory_apply_required_attribute_to_necessary_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appuser_remove_nav_prop_tickethistories___tickethistory_apply_required_attribute_to_necessary_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "201804020115572_appuser_remove_nav_prop_tickethistories___tickethistory_apply_required_attribute_to_necessary_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
