// <auto-generated />
namespace Bugtracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ticket_applied_required_to_necessary_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ticket_applied_required_to_necessary_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "201804012318301_ticket_applied_required_to_necessary_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
